# Generated by Django 5.1.6 on 2025-02-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('condition', models.DecimalField(decimal_places=1, max_digits=3)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
